import Head from 'next/head'
import Banner from './components/Banner'
import Button from './components/Button'
import Listmanga from './components/Listmanga'
import Navbar from './components/Navbar'
import styled from 'styled-components'
import Footer from './components/Footer'
import Slider from './components/Slider'

const Div = styled.div`
background:#1C1C1C;
`

export default function Home() {
 

  return (
    <div >
      <Head>
        <title>Yey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <Slider />
      <Div>
      <Listmanga />
      <Listmanga />
      <Listmanga />
      <Listmanga />
      <Listmanga />
      <Button />
      </Div>
      <Footer />
      
    </div>
  )
}
